// let's imagine this file is autogenerated from the backend
// ideally, we want to keep these api related types in sync
// with the backend instead of manually writing them out
import { type Member, type Replycant } from "./tables/forTables";

export type BaseEntity = {
    id: string;
    createdAt: number;
};

export interface AuthTokenResponse {
    access_token: string;
    token_type: string;
}

export type Entity<T> = {
    [K in keyof T]: T[K];
} & BaseEntity;

export type User = Entity<{
    id: number;
    firstName: string;
    lastName: string;
    middle_name: string;
    email: string;
}>;

export type LoginResponse = {
    access_token: string;
    token_type: string;
};



export type Project = {
    id: number;
    tag: string;
    tagVariant:
        | "error"
        | "type"
        | "disabled"
        | "default"
        | "info"
        | "warning"
        | "success"
        | "secondary"
        | undefined;
    title: string;
    description: string;
    progressValue: number;
    dateText: string;
    tags: { text: string }[];
    membersCount: number;
    users: { name: string }[];
    archived: boolean;
};

export type ProjectRole = {
    title: string;
    tasks: string[];
    count: number;
};

export interface ProjectSingle extends Project {
    spaceId: number;
    descriptionExtended: string;
    creationDate: string;
    color: string;
    roles: ProjectRole[];
    members?: Member[];
    replycants?: Replycant[];
}

export interface SpacesListParams {
    page?: number;
    limit?: number;
}




export type SpacesListResponce = {
    categories: { name: string }[];
    spaces: Space[];
    page?: number;
    limit?: number;
    total?: number;
};


export type Space = {
    id: number;
    title: string;
    projectsCount: number;
    membersCount: number;
    color: string;
    category: string;
    description: string;
};

// export interface Space {
//     id: number;
//     name: string;
//     author_id: number;
//     status_id: number;
// }

// export interface SpacesListResponce {
//     data: Space[];
//     // Или если ответ — это массив напрямую:
//     // spaces: Space[];
// }

export type NotificationType = "mention" | "request" | "join";

export interface Notification {
    id: number;
    type: NotificationType;
    name: string;
    action: string;
    project: string;
    time: string;
    avatar: string;
    read: boolean;
}
