// let's imagine this file is autogenerated from the backend
// ideally, we want to keep these api related types in sync
// with the backend instead of manually writing them out

export type BaseEntity = {
    id: string;
    createdAt: number;
};

export type Entity<T> = {
    [K in keyof T]: T[K];
} & BaseEntity;

export type User = Entity<{
    id: number;
    firstName: string;
    lastName: string;
    middle_name: string;
    email: string;
}>;

export type LoginResponse = {
    access_token: string;
};

export type Space = {
    id: number;
    title: string;
    projectsCount: number;
    membersCount: number;
    color: string;
    category: string;
    description: string;
};

export type Project = {
    id: number;
    tag: string;
    tagVariant:
        | "error"
        | "type"
        | "disabled"
        | "default"
        | "info"
        | "warning"
        | "success"
        | "secondary"
        | undefined;
    title: string;
    description: string;
    progressValue: number;
    dateText: string;
    tags: { text: string }[];
    membersCount: number;
    users: { name: string }[];
    archived: boolean;
};

export type SpacesListResponce = {
    categories: { name: string }[];
    spaces: Space[];
    role: "root" | "admin" | "manager" | "member";
};

export type NotificationType = "mention" | "request" | "join";

export interface Notification {
    id: number;
    type: NotificationType;
    name: string;
    action: string;
    project: string;
    time: string;
    avatar: string;
    read: boolean;
}
